# Generated by Django 3.1 on 2020-08-07 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktracker',
            name='end_time',
            field=models.TimeField(blank=True),
        ),
    ]
